### ISSUE TITLE
Automatic restart doesn't work on a reboot

### ISSUE THREAD

**Issue by mstang** [marsbard/puppet-alfresco#101]
Periodically, I will restart my VM where Honeycomb is running and while the server starts, I can't log in.  I have to stop the server (catalina.sh stop) and restart it (catalina.sh start), then when it comes up, everything is fine.

**Comment by digcat** [comment]
Hi Mark

THe honeycomb build is designed to be started with service tomcat stop / 
service tomcat start.  Can you try using that and see if you experience 
the same issue.  I've not seen that issue before during testing, so 
might be related.  Also how much ram are you giving to the vm?

regards

Daren

**Comment by mstang** [comment]
Hi Daren,
I have the VM configured for 3G to match my production environment.  I haven't tried the to stop and start it with the "service" command.  As soon as my environment reboots I will give it a try!  Thanks!

How is the install configured?  Does it use the service command to start the server?

regards,

Mark

**Comment by digcat** [comment]
hi mark

Yes, so as root, service tomcat stop, service tomcat start should do the trick.  

cheers

Daren

**Comment by mstang** [comment]
OK, tracked it down to the script looking for and finding older versions of openjdk and using that instead of my Oracle 8 java.
sudo apt-get purge openjdk* is my friend ;-)

Thanks!

Mark

**Comment by digcat** [comment]
ok closing this issue then.
