### ISSUE TITLE
cant install on centos 6.7 

### ISSUE THREAD

**Issue by woakes070048** [marsbard/puppet-alfresco#104]
Could not parse options: invalid option: --hiera_config=install/hiera.yaml

**Comment by digcat** [comment]
this is a warning, and not something to worry about, puppet should have continued, is this still an issue ?

**Comment by digcat** [comment]
also noticed issue with redhat-release

[admin@honeycomb install]$ more /etc/redhat-release 
CentOS release 6.7 (Final)
[admin@honeycomb install]$ vi inc-puppet.sh 
[admin@honeycomb install]$ head -n1 /etc/redhat-release | cut -f4 -d\ | cut -f1 -d.
(Final)

this actually  is causing the first issue with hiera,

quick hack to get working modify install/inc-puppet.sh and replace the pattern with EL_VER with 6 to ensure you get the correct rpm installed.  

We need a better way for ensuring the correct OS version

**Comment by woakes070048** [comment]
I will try that and see if it all installs and let you guys know.

**Comment by digcat** [comment]
I've put a patch into dev-1.1 which you can try using git checkout 
dev-1.1 after the initial git clone.

**Comment by woakes070048** [comment]
i am still getting the same error. do you know if any logs i can check i cant find anything in /var/log

**Comment by digcat** [comment]
make sure you have the latest git copy, you may already have installed 
an older version of puppet,

puppet --version
3.8.3
is what you should have,

if you have older 2 version, do a yum remove puppet, then rerun sudo 
./install.sh to pull in the new version.

**Comment by woakes070048** [comment]
I have the latest copy and i have puppet version 2.7.26

**Comment by digcat** [comment]
thats your problem, do a yum remove on puppet, you should have the same 
version as i just sent, its most likely pulling in the wrong rpm, which 
was the issue you uncovered.  Id not seen it as I use centos 7, so a 
good catch :)  need to remove the rpm, then let install.sh pull in the 
right one

**Comment by woakes070048** [comment]
okay i got it installed in a vagrant machine that i just spun up and it was the puppet 2.7.26. the biggest problem that i have is i am using katello as an enc and that installed the puppet agent. Thanks for the help.

**Comment by digcat** [comment]
ahh cool, if you see anything we can add to improve the build do let us 
know.  havent seen katello, but it looks interesting will have a read.

**Comment by woakes070048** [comment]
I dont know if you have heard of the foreman but it that on steroids

**Comment by digcat** [comment]
nice! we have been using foreman, does it work across OS ie ubuntu and 
centos

**Comment by woakes070048** [comment]
i have only been using it for centos 6 and 7 but it does everything the foreman does. Have you gotten this to run from foreman?

**Comment by digcat** [comment]
yes it should, although havent tested again since it was, so let us know 
your mileage!

**Comment by woakes070048** [comment]
I will have one of my techs try and get back to you.

**Comment by digcat** [comment]
excellent cheers.

**Comment by digcat** [comment]
sure thanks, any feedback welcome.
