### ISSUE TITLE
error  whene I install Alfresco on xenial Ubuntu 16.04  -  oracle-java8-installer

### ISSUE THREAD

**Issue by mathieuga** [marsbard/puppet-alfresco#121]
Hi,
Like Ubuntu 14, xenial Ubuntu 16.04 have install error on oracle-java8-installer.

_Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install                   oracle-java8-installer' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  binutils gsfonts-x11 java-common libfontenc1 libxfont1
  oracle-java8-set-default x11-common xfonts-encodings xfonts-utils
Suggested packages:
  binutils-doc binfmt-support visualvm ttf-baekmuk | ttf-unfonts
  | ttf-unfonts-core ttf-kochi-gothic | ttf-sazanami-gothic ttf-kochi-mincho
  | ttf-sazanami-mincho ttf-arphic-uming firefox | firefox-2 | iceweasel
  | mozilla-firefox | iceape-browser | mozilla-browser | epiphany-gecko
  | epiphany-webkit | epiphany-browser | galeon | midbrowser
  | moblin-web-browser | xulrunner | xulrunner-1.9 | konqueror
  | chromium-browser | midori | google-chrome
The following NEW packages will be installed:
  binutils gsfonts-x11 java-common libfontenc1 libxfont1
  oracle-java8-installer oracle-java8-set-default x11-common xfonts-encodings
  xfonts-utils
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 3134 kB of archives.
After this operation, 15.6 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  oracle-java8-installer oracle-java8-set-default
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
Error: /Stage[deps]/Alfresco::Packages/Package[oracle-java8-installer]/ensure: change f                  rom purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=-                  -force-confold install oracle-java8-installer' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  binutils gsfonts-x11 java-common libfontenc1 libxfont1
  oracle-java8-set-default x11-common xfonts-encodings xfonts-utils
Suggested packages:
  binutils-doc binfmt-support visualvm ttf-baekmuk | ttf-unfonts
  | ttf-unfonts-core ttf-kochi-gothic | ttf-sazanami-gothic ttf-kochi-mincho
  | ttf-sazanami-mincho ttf-arphic-uming firefox | firefox-2 | iceweasel
  | mozilla-firefox | iceape-browser | mozilla-browser | epiphany-gecko
  | epiphany-webkit | epiphany-browser | galeon | midbrowser
  | moblin-web-browser | xulrunner | xulrunner-1.9 | konqueror
  | chromium-browser | midori | google-chrome
The following NEW packages will be installed:
  binutils gsfonts-x11 java-common libfontenc1 libxfont1
  oracle-java8-installer oracle-java8-set-default x11-common xfonts-encodings
  xfonts-utils
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 3134 kB of archives.
After this operation, 15.6 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  oracle-java8-installer oracle-java8-set-default
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
Notice: /Stage[main]/Alfresco::Addons::Ootbfrontpage/Vcsrepo[/var/www/vps359542.ovh.net                  ]: Dependency Package[oracle-java8-installer] has failures: true
Warning: /Stage[main]/Alfresco::Addons::Ootbfrontpage/Vcsrepo[/var/www/vps359542.ovh.ne                  t]: Skipping because of failed dependencies_

So like Ubuntu 14 lunch "apt-get install oracle-java8-installer" for solve this issue

**Comment by digcat** [comment]
Hi mathieuga 

Thank you for your post.  However, we are using the oracle-java8-installer, which you can see in packages.pp. 

https://github.com/marsbard/puppet-alfresco/blob/master/manifests/packages.pp

        package { 'oracle-java8-installer':
          ensure => present,
        }

what xenial install are you using? have noticed some vagrant boxes of xenial throw up issue on java, but using a full clean xenial box, havent noticed this problem.

**Comment by mathieuga** [comment]
I using the Ubuntu 16.04 provide by OVH.
So I think it is not a full clean xenial box.

Think
