### ISSUE TITLE
Review Alfresco Security best practices and integrate where necessary

### ISSUE THREAD

**Issue by marsbard** [marsbard/puppet-alfresco#13]
http://www.slideshare.net/toniblyx/alfresco-security-best-practices-check-list-only

**Comment by digcat** [comment]
some of these were enourmous values, but guess some sort of hardening would be useful, are there any tools which might help with this, think we are into new territory

**Comment by marsbard** [comment]
I think I have already applied most of this where it was relevant, it's still open so I can check if anything is left (and because I am too lazy to comment when I work on an issue)

**Comment by digcat** [comment]
ok port 8080 is one security issue closed, guess moving ssh, doing sudo 
on user and preventing root login might be the other ones, although 
benefit for dev is minimal, only if used in production, its also 
something that would need config from go.pp i think, else everyone would 
get same port too.
