### ISSUE TITLE
Sharepoint support in reverse proxy

### ISSUE THREAD

**Issue by marsbard** [marsbard/puppet-alfresco#18]
When configuring reverse proxy, allow for sharepoint config

30/1/15 # alfresco
```
	<faugusztin> marsbard: in that case don't forget about sharepoint ;)
	<marsbard> you mean in front of alfresco faugusztin? unfortunately I will not be considering that option ;-)
	<faugusztin> marsbard: well you were talking about reverse proxy & apache
	<faugusztin> marsbard: you can proxy the sharepoint protocol there too, but it of course needs configuration steps in vti.properties inside alfresco
	<Loftux> marsbard: I'm looking at refactor the config added for nginx to follow the /etc/nginx/conf.d/ approach in my ubuntu install script. With that i can add a couple of different sample config files with just the default enabled.
	<Loftux> That includes a pre-config for sharepoint module.
	<marsbard> faugusztin: obviously Loftux understood what you said better than I did ;-)
	<marsbard> I see what you mean, thanks
	<marsbard> Loftux: heiko mentioned to me that he could not get nginx to work with webdav or spp, sounds like you have different experiences?
	<faugusztin> marsbard: ok, i say it in a different way. You have alfresco on tomcat running at port 8080 and sharepoint in port 7070. You can reverse proxy them both behind a single apache/nginx under different URL - but in that case you need to do some vti.properties modifications inside the alfresco install, that is all i tried to say :)
```

**Comment by marsbard** [comment]
`<Loftux> Yes, I've used this https://github.com/loftuxab/alfresco-ubuntu-install/blob/master/nginx/nginx.conf#L182 Instead of having it in one file and commented out, I'm going to put it in its own file
	<alfbot> Title: alfresco-ubuntu-install/nginx.conf at master · loftuxab/alfresco-ubuntu-install · GitHub (at github.com)
	<Loftux> The trick is to use a separate domain, I haven't been able to get it to run under the same domain as /alfresco, /share
	<faugusztin> Loftux: an nginx limitation ?
	<Loftux> faugusztin: I think not, sharepoint clients do make root requests, and those get forwarded to the wrong place if sharing with alfresco. So if you something like office.example.com, you can have everything go to localhost:7070
	<faugusztin> Loftux: you mean that. yeah, we handled it via different port :)`

**Comment by marsbard** [comment]
I hate github markdown

**Comment by marsbard** [comment]
from faugusztin:

In Apache SSL configuration file :

ProxyRequests Off
RewriteEngine On
ProxyPass / http://127.0.0.1:7070/
ProxyPassReverse / http://127.0.0.1:7070/

In vti.properties :
vti.server.port=7070
vti.server.protocol=http
vti.server.url.path.prefix=/alfresco
vti.server.external.host=your_apache_hostname
vti.server.external.port=443
vti.server.external.protocol=https
vti.server.external.contextPath=/alfresco

**Comment by marsbard** [comment]
apache port 80 is redirected to alfresco share running on let's say 8080
apache port 443 (SSL) is redirected to Alfresco Sharepoint interface running on port 7070
 but the catch is in the vti.server.external settings in vti.properties
they define the URL's the sharepoint vti service will return

**Comment by marsbard** [comment]
```
<marsbard> well thinking about it we could run it on "/" while still proxying "/alfresco" "/share" etc
<marsbard> maybe...
<marsbard> although it would be really useful to override "/index.html" in that instance
<digcat> yep worth a try to keep it contained
<marsbard> hmm, problem with that... if people just go to "https://<domain_name>" they will just get some bullshit gibberish, whatever gets served on 7070
<marsbard> not too bad, gives a message and a URL to connect to, but mentions obsolete explorer link as well as share
<marsbard> trying to work out if we can overwrite that file it serves with something else ;-) #sneakyhack
<marsbard> although might not be a file, it may be served up by java source
<marsbard> aha! https://github.com/Alfresco/community-edition/blob/c44ea9034b5a8573ecf214ebbc6adcfcc8a02970/modules/sharepoint/amp/config/alfresco/templates/org/alfresco/vti/welcome-info.html.ftl
<marsbard> that file is inside this jar: tomcat/webapps/alfresco/WEB-INF/lib/alfresco-spp-5.0.c.jar
<digcat> good find
<marsbard> so at a pinch if it does work with that configuration we could hack that in
<marsbard> just to redirect to /share really, no content required
```

**Comment by digcat** [comment]
tested with Office 2007, with self cert you get only read only access via spp

**Comment by digcat** [comment]
Creating a space through SPP - not successful:
   
 Tried to create a space (right click -> New Folder) using SPP but it would only save as space with name "New Folder" (Windows does it that way)
  Then tried renaming the space through SPP. This did not work resulting in "Cannot read from source disk - Try again"

    Reverted to creating a space called SPP Test using Share (renaming space also ok obviously)

Saving a new document into alfresco through SPP - not successful:

    Tried to create a new XSLX document and save into SPP Test space - get a message box result of "Document Not Saved"
    Ended up dragging my created document SPP Test.xlsx in through Share

Editing documents already in alfresco - successful:
    Opened the SPP Test.xlsx document through SPP
    Edited and saved successfully with the version incrementing correctly

**Comment by digcat** [comment]
from testing this is working as expected

**Comment by JialuZhang** [comment]
@marsbard 

In your Apache SSL configuration file :

```
ProxyRequests Off
RewriteEngine On
ProxyPass / http://127.0.0.1:7070/
ProxyPassReverse / http://127.0.0.1:7070/
```

the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".

Since herein there is no "RewriteRule" in this directory, for security issue, deleting “RewriteEngine On” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```

**Comment by douglascrp** [comment]
@JialuZhang I am sorry to inform you, but unfortunately @marsbard  has passed away, and because of that, this project is no longer updated.
I hope another contributor can answer your question

**Comment by JialuZhang** [comment]
@douglascrp 

Thanks for your reply. I am sorry to hear that. My condolence.

We are a group of researchers from Yale University. Our goal is to build an automated tool to detect silent misconfigurations in user's repo. This comment is generated by our system and we hope our tool could benefit the other users who have the similar issue. That is the reason we posted here. Thank you!
