### ISSUE TITLE
add reverse proxy for ssl support

### ISSUE THREAD

**Issue by marsbard** [marsbard/puppet-alfresco#19]
This is the user experience I plan to implement

## SSL Configuration ##

The `alfresco::install::proxy` module takes an argument `ssl_cert_path` _(which 
is passed to it by `alfresco::init` and can be passed in there)_ and it expects
to find there a `.cert` file and a `.key` file named for your domain, so for 
example if your domain is 'demosite.orderofthebee.org' you would arrange for 
your key+cert files to be in the `ssl_cert_path` location and then puppet would try 
to retrieve:

    demosite.orderofthebee.org.key
    demosite.orderofthebee.org.cert

from the `ssl_cert_path` location.

If `ssl_cert_path` starts with "http" then puppet will attempt to download the 
files by appending `/demosite.orderofthebee.org.key` or `/demosite.orderofthebee.org.cert`
as appropriate to `ssl_cert_path`.

If no `ssl_cert_path` is given then new self-signed certificates will be generated

**Comment by digcat** [comment]
hi martin

im having problems with the ssl from local disk, im seeing this error on puppet build

==> default: Invalid parameter ssl_cert_path at /tmp/vagrant-puppet/manifests-5058f1af8388633f609cadb75a75dc9d/go.pp:18 on node precise64.home
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what

at which point it dies,

ive added 	ssl_cert_path => '../mydocs-certificates'
to my go file, ive also tried an absolute path, but still no joy on vagrant build

**Comment by digcat** [comment]
tested on self signed, and real certificate, works a treat.

**Comment by marsbard** [comment]
Closing as fixed, any issues, reopen
