### ISSUE TITLE
latest develop branch giving me

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#29]
==> default: err: /Stage[main]/Alfresco::Service/Service[alfresco-start]/ensure: change from stopped to running failed: Could not start Service[alfresco-start]: Execution of '/etc/init.d/tomcat7 start' returned 1:  at /tmp/vagrant-puppet/modules-4e24c87ff7f311bab44febde2d31282c/alfresco/manifests/service.pp:15
==> default: notice: /Stage[main]/Alfresco::Service/Service[alfresco-start]: Triggered 'refresh' from 5 events
==> default: notice: /Stage[main]/Alfresco/Anchor[alfresco::end]: Dependency Service[alfresco-start] has failures: true
==> default: warning: /Stage[main]/Alfresco/Anchor[alfresco::end]: Skipping because of failed dependencies
==> default: notice: Finished catalog run in 825.65 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

and in tomcat catalina

OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fb3aa660000, 34185281536, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 34185281536 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /opt/alfresco/tomcat/hs_err_pid16895.log

**Comment by digcat** [comment]
yes can see mx options in /etc/default/tomcat7 are now 32G, nice if youve got it !

**Comment by marsbard** [comment]
does it say 32G in your go.pp file? Mind you I haven't seen it try to allocate that mem when the setting is high, however I do tend to use 2G in that file.

**Comment by digcat** [comment]
Ahhh the mem xmx setting came in as 32G ! Oops


Sent from Samsung Mobile

-------- Original message --------

**Comment by marsbard** [comment]
No worries, sorry I have never seen it try to allocate the mem before :-)
