### ISSUE TITLE
iptables is restarted on every puppet run

### ISSUE THREAD

**Issue by marsbard** [marsbard/puppet-alfresco#41]
Notice: /Stage[main]/Alfresco::Install::Iptables/Exec[/etc/init.d/iptables restart]/returns: executed successfully

need to work out a way to not restart, probably involve looking for one of the rules we set in the output of `iptables -nvL` or `iptables -t nat -nvL`

**Comment by digcat** [comment]
im also experiencing some problems using build now from vagrant.  so currently, if i specify a domain name in go.pp, i need a dns to resolve it, so as a hack i update the hosts file in the vm.  which works fine, however, i getting hanging when trying to hit the client,  dont think tests will pick up problem in travis, as they hit localhost.  anyway have just pulled develop again, and am rebuilding, so will update here in a bit.

**Comment by marsbard** [comment]
fixed
