### ISSUE TITLE
accessing /alfresco/cmisatom externally

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#42]
im seeing issues when trying to connect to /alfresco/cmisatom which interferes with cmis operations.

**Comment by marsbard** [comment]
it's working ok for me, from external address visiting https://<server>/alfresco/cmisatom yields an xml file as expected? Do you see the same? If so what error condition are you seeing?

**Comment by marsbard** [comment]
to be fair I haven't actually used any cmis tools against that url

**Comment by digcat** [comment]
im seeing the xml as well when visiting in a browser, its just the cmislib access,  will get a test together for it.

**Comment by digcat** [comment]
have added a simple test for cmis, simply can it login to the Main Repository.  anyway, can close this, my issue with resolving for vagrant.
