### ISSUE TITLE
add duplicity to build

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#43]
once build is complete and running, looking in the vm duplicity hasnt been installed.

root@vagrant-ubuntu-trusty-64:~# apt-get install duplicity
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libxfont1 libxkbfile1 x11-xkb-utils xfonts-base xfonts-encodings
  xfonts-utils xserver-common xserver-xorg-core
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  librsync1 python-lockfile
Suggested packages:
  python-paramiko python-oauthlib python-boto ncftp python-cloudfiles lftp
  python-gdata tahoe-lafs python-swiftclient
The following NEW packages will be installed:
  duplicity librsync1 python-lockfile
0 upgraded, 3 newly installed, 0 to remove and 100 not upgraded.
Need to get 245 kB of archives.
After this operation, 1,366 kB of additional disk space will be used.
Do you want to continue? [Y/n]

**Comment by marsbard** [comment]
So there is backup.pp but it was really only set up for the puppetmaster case.

I refactored bashconf to its own project https://github.com/marsbard/bashconf so now there is a configurator that can be run with the "backup.sh" command (probably misnamed, should be changed). But this only helps the vagrant build. To be useful in the standalone build these need to be copied into place in the server too.

**Comment by marsbard** [comment]
I think this is probably a matter of documenting how to set up the backups. Once the backups puppet manifest is applied it pulls in duplicity and sets up BART how you want.

**Comment by digcat** [comment]
ok installing bart.

darenf@darenf-HP-ProBook-4340s:~/work1$ ./modules/alfresco/setup-backup.sh 
loading config/backup_pre.sh

======================================================
Bash Configurator https://github.com/marsbard/bashconf
======================================================

Idx	Param                     Value

[1]	backuptype                local
[2]	backup_at_hour            2
[3]	backup_at_min             0
[4]	duplicity_password
[5]	local_backup_folder       /mnt/backup
[6]	fulldays                  30D
[7]	backup_policies_enabled   true
[8]	clean_time                12M
[9]	maxfull                   6
[10]	volume_size               25
[11]	duplicity_log_verbosity   4

Please choose an index number to edit, A to apply configuration, or Q to quit
 -> A

0 errors
Installing...
Writing answer file config/backup_answers.sh
Writing puppet file do_backup.pp
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class alfresco::backup at /home/darenf/work1/modules/alfresco/do_backup.pp:25 on node darenf-hp-probook-4340s.home
Wrapped exception:
Could not find declared class alfresco::backup
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class alfresco::backup at /home/darenf/work1/modules/alfresco/do_backup.pp:25 on node darenf-hp-probook-4340s.home

**Comment by marsbard** [comment]
ok looks like an error with paths, thanks for the report
