### ISSUE TITLE
latest build for 5.0.x gives broken previews

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#49]
adding any ods file gives a 'This document can't be previewed.'  this was working fine, and im not seeing any errors in catalina.  will try testing to isolate, but it was working fine, so not sure if this is a hangover from java 8 upgrade or some other recent upgrade

**Comment by marsbard** [comment]
Result of interaction between java 8 and libre office. Closing now as we are sticking to java 7 for initial release
