### ISSUE TITLE
add a nice 503 page while alfresco loads

### ISSUE THREAD

**Issue by marsbard** [marsbard/puppet-alfresco#55]
currently apache proxy times out with 503 if alfresco isn't ready; make a nice looking 503, preferably with an implicit reload

**Comment by marsbard** [comment]
"We'll bee with you in a moment" :-D

**Comment by marsbard** [comment]
Err no issue for the home page so attaching it here, where is the home page?

![selection_001](https://cloud.githubusercontent.com/assets/197057/7902805/c095c26e-07c6-11e5-8053-909b84ce6c67.png)

**Comment by digcat** [comment]
yep, its still looking for a load of javascript and css, needs stripping out

**Comment by marsbard** [comment]
Once share has come up properly the elements load ok. But I thought the point of a home page was to add useful links and content, not just to copy the login form

**Comment by digcat** [comment]
have created a 503.html needs to be placed somewhere to overwrite, can see on fresh install using /503.html which redirects to /index.html
