### ISSUE TITLE
AAAR module

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#59]
breaks the dashboard for version 5.0.x
reproduce, by deleting the showcase panel, leaves dashboard in a strange single column, and resizing the page the remaining panels overlap unlike system without module.

**Comment by marsbard** [comment]
Couldn't replicate, at least on the admin dashboard
![screenshot from 2015-05-27 20 37 34](https://cloud.githubusercontent.com/assets/197057/7846371/6167a5ca-04bd-11e5-882e-ee980cc3439d.png)

**Comment by digcat** [comment]
Still seeing problems, screen scrunching up on admin console

![screenshot from 2015-05-28 05 10 58](https://cloud.githubusercontent.com/assets/4847462/7852741/7f86a096-04fa-11e5-9c0b-bf5170af4767.png)
![screenshot from 2015-05-27 21 46 52](https://cloud.githubusercontent.com/assets/4847462/7852742/7f8c5f2c-04fa-11e5-9ef6-93f032fd9209.png)

**Comment by marsbard** [comment]
Is it OK in chrome? What about clearing the firefox cache / try a firefox on a different machine?

**Comment by digcat** [comment]
chrome looks fine, also seems to work better under java 8.  have reenabled in dev-1.1 although i notice the menu still shows.

**Comment by fcorti** [comment]
Here I am with more tests with dev 1.1 (sorry for delay).
On Ubuntu I cannot repeat the issue.

Below what I get on Firefox:
![image](https://cloud.githubusercontent.com/assets/6010860/8766494/58ac7bb2-2e3a-11e5-9500-e3715acfe62e.png)

Below what I get on Chrome:
![image](https://cloud.githubusercontent.com/assets/6010860/8766496/69bc67e6-2e3a-11e5-8976-2e0b061b6e5e.png)

Instead of following the issue, what about if I develop a dashlet for AAAR analytics?

**Comment by digcat** [comment]
Hi Francesco

A dashlet would be great, so then the standard interface wont be changed.  I tested this again the other day, and got better results, although I had to pull it again due to issues at sourceforge.  Was wondering, might you do a tag release on github, then we can pull the amps from github?  We need it as a release to avoid a weird timeout problem.

Cheers

Daren

**Comment by fcorti** [comment]
You are right Daren.
In the past days I faced too, with sourceforge problems.
Ok, I'll define a tag release for them on github and let you know.
Ok also for AAAR dashlet... I'll work on it.
Will let you know asap.

**Comment by fcorti** [comment]
Test: Pentaho with reverse proxy
On a Pentaho BA server, I installed apache2 with mod_proxy.
`sudo apt-get install apache2
sudo a2enmod proxy_http
sudo service apache2 restart`
Then I develop a fool example with a reverse proxy from port 80 to 8180 on localhost.
`sudo nano /etc/apache2/mods-enabled/proxy.conf`
`<VirtualHost *:80>
  ProxyPreserveHost On
  ProxyRequests Off
  ProxyPass / http://localhost:8180/
  ProxyPassReverse / http://localhost:8180/
</VirtualHost>`
`sudo service apache2 restart`
Accessing to AAAR and Pentaho using `http://<ip>` everything works properly.
@digcat: could add some comments describing your test case?
Using my test case everything seems to work properly.
Many thanks.

**Comment by fcorti** [comment]
Hi @digcat,

Here you can find the first release of the AMP file with the AAAR Dashlet instead of the Alfresco menu.
https://sourceforge.net/projects/aaar/files/Alfresco%20AMP%20packages/v1.1/

During the next days I'll release it again with some secondary improvement.
For our tests of integration, it should work.

I wait your tests. 
Please let me know you need support on it.

Cheers.

**Comment by digcat** [comment]
Hi Francesco

Excellent, any chance of putting on a tag release on github?  you just 
caught me, as Im about to call it a night, will give this some time 
tomorrow, cheers

Daren

**Comment by fcorti** [comment]
Sure... I'll write you tomorrow to share some details.

Thanks.

**Comment by fcorti** [comment]
Hi @digcat,

Now the AMP packages are also on github.
I would like to maintain the archive of the versions in the build folder.
Now the AAAR item in the menu is hide by default and a brand new AAAR Dashlet is available.
Below the link to the AMPs.

Alfresco repository AMP:
https://github.com/fcorti/alfresco-audit-analysis-reporting/tree/master/aaar-alfresco/build/v1.1

Alfresco Share AMP:
https://github.com/fcorti/alfresco-audit-analysis-reporting/tree/master/aaar-alfresco-share/build/v1.1

In the next days I'm going to release the AMPs for other Alfresco versions and some new tests.
In any case the integration with Alfresco OOTB could start.

Cheers.

**Comment by digcat** [comment]
Hi Francesco

Love your work !!  just one thing, i tried using the urls to get the 
amps, but think this is the issue i mentioned before, github seems to 
have some issue when pulling files directly from a branch, where as if 
you do a Tag Release, it has no issue.

https://github.com/blog/1547-release-your-software

I don't know why it should be like this, but I had the same issue with 
the honeycomb-beetheme, and making a tag release made the downloads nice 
and reliable.

thanks hope this isn't too much of an inconvenience, cheers

Daren

**Comment by fcorti** [comment]
Hi Daren,

Thank you for your quick answer.
It's the third time you ask me to tag the releases in GitHub... and seems I prefer not to do it. :-D
Of course this is not what I think so I'm going to do it and back to you.

While I'm completing the task, please, let me know if you find problems in your tests.

Cheers,

-F

**Comment by fcorti** [comment]
Hi Daren,

Here you can find the AAAR v3.1 release.
https://github.com/fcorti/alfresco-audit-analysis-reporting/releases/tag/v3.1

Cheers,

-F

**Comment by digcat** [comment]
Excellent!! yes, that does the trick, have added to dev-1.1, and your 
addon loads lovely, and love the dashlet!!

So have noticed an issue, trying to roll pentaho into the build, in 
that, we have to have java 8 for 5.0.d as it stands, and I note Pentaho 
needs Java 7 (long long thread in irc, for some reason a flag to support 
java 7 was not set for community, but it was for enterprise!, any way 
alfresco are apparently back tracking as they have to support ibm java 
7, which hasnt been EOL, like Java 7 has, but wont happen till next 
release for community)

So building pentaho on its own box looks to be the better way to go.  
But how do we update the address for pentaho, from outside the amp?   
Ideally Id like to be able to specify the address for pentaho in the 
config in install.sh, so that the addon is good to go, currently i see 
its set to localhost:8081

anyway, as far as step one goes, this looks grand to at least get the 
add on in place.

cheers

Daren

**Comment by fcorti** [comment]
Nice Daren... sounds very good (and thank you for the feedback).

Yes, Pentaho runs with java 7 until th latest version (5.4.x) so, if I understand correctly, the choice to run it with its own java 7 is the right choice also for the future releases (Alfresco and Pentaho will have parallel paths and releases, of course).

Again, if I understand correctly, you are developing the puppet also for installing Pentaho and AAAR.
This would be perfect instead of limiting to the AMPs.
If this is confirmed, please, let's check together about dependencies and settings because is not enough to install "only" Pentaho.

Coming to your question:
But how do we update the address for pentaho, from outside the amp?

The answer is:
Updating the url attribute of the link tags of the file below.
https://github.com/fcorti/alfresco-audit-analysis-reporting/blob/master/aaar-alfresco-share/src/main/amp/config/alfresco/web-extension/site-webscripts/com/fcorti/AAAR/components/dashlet/AAAR.get.config.xml

This is not exactly "outside the AMP" but today it's work like this...

Do you imagine something different?
I could develop it. ;-)

**Comment by digcat** [comment]
Hi Francesco

Yes, I did see the config in AAAR.get.config.xml.  I was wondering if at 
all possible whether we might be able to override the url from inside 
alfresco-global.properties?  Then we could provide that to alfresco 
before the system first starts, ensuring the urls are good to go.

**Comment by fcorti** [comment]
Mmm... sounds good.
I'll back to you once the setting will be ready.

Until then, please let me know when I could test a working version.
I would like to see it in action. :-)

**Comment by digcat** [comment]
have added to dev-1.1 the addon, it loads fine, think the dashlet 
approach is great!  if we could have a param in 
alfresco-global.properties, ie like

aaarserverurl=http://someaddress:port

which then overrides the dashlet urls, then providing the pentaho server 
is available, and

# Alfresco Audit service
audit.enabled=true
audit.alfresco-access.enabled=true

are set, then the stats should start streaming,

cheers

Daren

**Comment by fcorti** [comment]
:+1:

**Comment by fcorti** [comment]
Hi Daren,

I have released the new v1.1 AMPs with the requested feature.
You can find the documentation here:
http://fcorti.com/alfresco-audit-analysis-reporting/aaar-advanced-configurations/alfresco-menu-to-aaar/

Please note that now is requested the repository AMP and the share AMP.
Now that I'm writing, is downloadable only the Alfresco 5.0.d version but in the nearest future I plan to release also the AMPs for the oldest versions (and EE).
Please note I renamed the AMP files you can find here:
https://github.com/fcorti/alfresco-audit-analysis-reporting/releases/tag/v3.1

Cheers.

**Comment by digcat** [comment]
Hi Francesco

Great, have updated the dev-1.1 release for 5.0d, I'll retest your new 
version and let you know how I go.  Ive got the pentaho side up and 
running on Ubuntu 14.04, but not yet fully working with alfresco, but 
getting there.  Will come back with feedback soon, cheers

Daren

**Comment by digcat** [comment]
Excellent job ! thats working perfectly, Ive added the params to 
alfresco-global.properties, commented out for now.  The urls flow 
through perfectly,

http://192.168.2.140:8080/pentaho/api/repos/%3Apublic%3AAAAR%3Amain.wcdf/generatedContent

can I confirm the address should be the same address as the bi-server, 
so I get to login to pentaho, on

http://192.168.2.140:8080/pentaho/Home

im still getting an error, but suspect something to do with the db setup 
on pentaho, so still working on that.

cheers for the changes,

Daren

**Comment by fcorti** [comment]
Great,

Please let me know if you need support on the installation of Pentaho (and AAAR, of course).

I didn't study the puppet scripts but I would like to have your opinion about a best practice (and recommendation from architectural point of view).
When informations and users becomes "heavy", Pentaho and Alfresco should be installed on separate servers (don't want to talk here about clusters or similar higher scalable solutions).
Do you plan to have a "modular" installation of Alfresco+AAAR addons and Pentaho+AAAR?
I mean: from the OOTB installation process, will be possibile to install only Alfresco+AAAR addons and only Pentaho+AAAR?

-F

**Comment by digcat** [comment]
Hi Francesco

Ah ha, yes the HA and large scale stories we have been talking about.  
At the moment, specifying mysql address in the ./install.sh causes mysql 
not to be installed locally, and a remote mysql to be used.  Im kinda 
thinking the same deal for AAAR, although having the alfresco AAAR side 
installed but not used wouldn't represent a major problem, and may make 
adding after initial install easier, but will talk with martin about 
that.  Martin has some excellent ideas on the HA/Clustering stories too, 
and will be looking at this more soon, and any ideas very welcome!

With regards the pentaho side of the install, Ive currently got it 
running locally on a vagrant vm, but will rebuild out in the wild, if I 
cant get the thing running.  One gotcha I've uncovered, is if you use a 
local mysql on alfresco, we lock the port down to localhost! so when 
pentaho tries to access it cant.  Will give this some more time today, 
so hopefully can get the final steps working. With regards puppet, we 
need to think about how to get the marketplace addons in place without 
needing the manual gui steps, as well as some of the manual configs.

With my current install, I just wanted to make sure the urls from aaar 
dashlet in alfresco are correct,  as Im seeing

Sorry. We really did try.
Something went wrong. Please try again
or contact your administrator.

when I click, 
http://192.168.2.140:8080/pentaho/api/repos/:public:AAAR:Reports:audit_creation.prpt/viewer
where I login to pentaho using http://192.168.2.140:8080/pentaho/Home


cheers

Daren

**Comment by fcorti** [comment]
I can help you to save your time. ;-)

[Manual installation of the Pentaho Modules from the marketplace]
There is a process I can give you to avoid using the interface.

[AAAR Error: Sorry. We really did try.]
The error you get is because AAAR is not yet installed.
http://fcorti.com/alfresco-audit-analysis-reporting/aaar-how-to-install/aaar-install/
Also in this case there is a AAAR_Install script you could use instead of the web interface.

Please let me know if prefer to discuss those topics here or others treads/issues?

-F

**Comment by digcat** [comment]
Excellent!, yes, scripts to build would make this a lot easier, Ill talk 
to Martin maybe we can get a hangout organised to discuss this in more 
detail, or another thread.  good to hear you have scripts to do the 
build outside the gui, that would help alot.

**Comment by fcorti** [comment]
Yep,
I'll wait for your contact.

Thank you for the support.

**Comment by digcat** [comment]
Hi Francesco

So with my pentaho build, I cant seem to get the AAAR module installed, 
I think its failing at the mysql driver level, but have tried upgrading 
to .36 and put where suggested but getting no where fast, I was 
wondering if you get a sec, whether you might cast an eye over the 
startup log, I'm hoping its something obvious and simple to correct, I 
was wondering if I have to use .19 driver for mysql? but struggling to 
find that.

running on ubuntu 14.04, the default DB

here is my startup log http://pastebin.com/JexM5CVH

This is just on my vagrant build, so I can get a handle on how it hangs 
together, should be catching up with Martin later today hopefully.  Cheers

Daren

**Comment by fcorti** [comment]
Hi Daren,

Sure I can check...
Looking at the log file, I don't like the message below:

    Cannot connect to database [${database

Please check you are passing the value of the variable and not the "code" of the variable and then back to me. I can check it again.

**Comment by digcat** [comment]
Ah ha, ok, seems i must have missed the standard install for 
libmysql-java, then I used spoon.sh to connect to it, and hooray AAAR 
installed and is customisable !!

**Comment by fcorti** [comment]
OH YEAH!!! :-D

**Comment by digcat** [comment]
Nice to end a friday with success!!!  have you managed to get honeycomb 
up against AAAR ?  Im just looking now at our Proxy config, and the port 
forwarding we do to hide 8080, and add the ssl, think its tripping up 
the AAAR_Extract.sh, but can see its a valid call, but with the self 
cert we hit that warning page.

so hitting url on alfresco directly

http://pastebin.com/88AjQH3A

but here is the log we get from extract

http://pastebin.com/pEjtiCdL

so think this is now getting to the nuts and bolts of problems were 
likely to hit.

anyway, its Friday, and time to knock off I feel while having some 
success.  If you have any thoughts on this that would be great, and will 
be back in touch when I touch base with Martin, cheers

Daren

**Comment by digcat** [comment]
and this

pentaho@vagrant-ubuntu-trusty-64:/tmp$ more AlfrescoAudit_1.json
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a 
href="https://testhoneycomb.digcat.com/alfresco/service/api/audit/query/alfresco-access?verbose=true&amp;limit=50000&amp;fromId=0">here</a>.</p>
</body></html>
pentaho@vagrant-ubuntu-trusty-64:/tmp$

so that explains the DOCTYPE error

**Comment by fcorti** [comment]
Thank you Daren... and have a beer for all of us.
I plan to test it in deep... but before I have to finish some tasks about support.

I'll tell you asap... have a nice weekend.

**Comment by fcorti** [comment]
Hi Daren,

I tried in a dev env but the something fails with a "minor major version" conflict on the AAAR AMP during the alfresco.war deploy... don't know why.

In any case, about the 301 error during the extraction, I think this could be caused by the https call that does not accept calls to the url.
As you can see the relative path of the URL is exactly the same and it works with http protocol and testhoneycomb.digcat.com server.
It seems to be a problem of access of the url.

Cheers,

-F

**Comment by digcat** [comment]
Ahh make sure your using the dev-1.1 branch.  yeah the 301 issue is down 
to a redirect were doing pushing the http to https, need to discuss with 
Martin our approach,

**Comment by fcorti** [comment]
Yes, I'm using the branch dev-1.1.
Java version 1.8.0.60.
Do you confirm?

**Comment by digcat** [comment]
Ah do you have java already installed, we install that,

openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)

although it should pick it up if its already installed.

**Comment by digcat** [comment]
adding to the 301 issue im seeing, I cant seem to get spoon.sh to follow 
301 redirects.  I can with wget, and curl, but dont have enough 
knowledge of spoon.sh, perhaps we cant do a permanent redirect?

**Comment by fcorti** [comment]
Hi Daren,

Also purging the Java I get the error below.
Tomorrow we will see...

    Caused by: java.lang.UnsupportedClassVersionError: com/fcorti/aaar/GetPropertiesWebScript : Unsupported major.minor version 52.0 (unable to load class $
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2961)
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1210)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1690)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:266)
        at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:419)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1270)
        ... 23 more

**Comment by fcorti** [comment]
About the 301 issue, I can help you with spoon, of course, but did you try customizing the `AAARConfiguration.xml` file?

You can find it here:
    https://github.com/fcorti/alfresco-audit-analysis-reporting/blob/master/pentaho/sparkl/aaar-CE-v5.3/endpoints/kettle/conf/AAARConfiguration.xml

Before installing AAAR, if you change the values below, you can set the right URL for the REST services.
    <parameter name="alfrescoHost" value="localhost"> </parameter>
    <parameter name="alfrescoProtocol" value="http"> </parameter>
    <parameter name="alfrescoPort" value="8080"> </parameter>

In any case, let me know I'll give you support on it (spoon comprised).

Cheers,

-F

**Comment by digcat** [comment]
Hi Francesco

The build ensures a valid java jvm is in place, so we test from an clean 
fresh vm based on ubuntu or centos, and rather than use Oracles Java, we 
use OpenJDK.  Unfortunately Ubuntu 14.04 doesnt ship with OpenJDK 8, so 
we pull that in during the build.  So in terms of coping with installed 
versions of java, we dont test that at all.

cheers

Daren

**Comment by digcat** [comment]
ok changing the AAARConfiguration.xml to use https, 
testhoneycomb.digcat.com and port 443.  I now hit the issue with the 
self certificate not being installed on the pentaho server,

2015/08/24 06:29:10 - Init audit staging - Starting entry [HTTP]
2015/08/24 06:29:10 - HTTP - Start of HTTP job entry.
2015/08/24 06:29:10 - HTTP - Connecting to URL: 
https://testhoneycomb.digcat.com:443/alfresco/service/api/audit/query/alfresco-access?verbose=true&limit=50000&fromId=0
2015/08/24 06:29:12 - HTTP - ERROR (version 5.4.0.1-130, build 1 from 
2015-06-14_12-34-55 by buildguy) : I was unable to save the HTTP result 
to file because of a I/O error: 
sun.security.validator.ValidatorException: PKIX path building fail
ed: sun.security.provider.certpath.SunCertPathBuilderException: unable 
to find valid certification path to requested target
2015/08/24 06:29:12 - HTTP - ERROR (version 5.4.0.1-130, build 1 from 
2015-06-14_12-34-55 by buildguy) : javax.net.ssl.SSLHandshakeException: 
sun.security.validator.ValidatorException: PKIX path building failed: 
sun.security.provider.certpa
th.SunCertPathBuilderException: unable to find valid certification path 
to requested target
2015/08/24 06:29:12 - HTTP -    at 
sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
2015/08/24 06:29:12 - HTTP -    at 
sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)

**Comment by digcat** [comment]
Im going to close this issue, as the Addon is now in the build, as per the original purpose of this ticket.
