### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by marsbard** [marsbard/puppet-alfresco#66]
Need a home page for e.g. `https://<hostname>/`

It should have some links for the main content:

- the Order website
- the github site (this one, marsbard/puppet-alfresco)
- the bouncy balls demo from the hackathon and any similar monitoring

It should have a form which matches the form at `https://<hostname>/share/page/`, i.e. it submits to the same place as that form without needing to use that form.

It should feature the Order logo, perhaps contact Oksana about look and feel (but timescales are compressed, better to beg forgiveness than ask permission ;-) ). Should have included her already for this stuff, wasn't thinking, we can update L+F with an early hotfix.

**Comment by digcat** [comment]
ok so have a page with the login details, which can be tailored, the only issue will be when logging out, share always returns you to /share/page.  to change the actual community graphics, would make a good addon amp i guess, is that the right way to do it?

**Comment by marsbard** [comment]
heh I was just thinking about that, was going to overwrite the alfresco logo with a bee :-P like just copying it in from the files/ folder

**Comment by marsbard** [comment]
returning to /share/page after logout, we will have to refer it to those who understand share a bit more I reckon

**Comment by marsbard** [comment]
we could actually redirect /share/page back to / in the apache proxy

**Comment by digcat** [comment]
ok have tackled this in a more standard way, and created a theme http://github.com/digcat/beeTheme.git so to get this live, it needs to have an xml file and be placed in themes folder? is that the right way ??? hate having to add anything into the war?

![screenshot from 2015-05-31 07 44 43](https://cloud.githubusercontent.com/assets/4847462/7900933/37dfccec-0769-11e5-9841-eb6e2f9c14b4.png)
![screenshot from 2015-05-31 07 44 23](https://cloud.githubusercontent.com/assets/4847462/7900932/37deb942-0769-11e5-811b-48ebcfcf8791.png)
![screenshot from 2015-05-31 07 44 06](https://cloud.githubusercontent.com/assets/4847462/7900934/37e38df0-0769-11e5-95ad-2626c1c15051.png)

**Comment by marsbard** [comment]
and the home page?

**Comment by digcat** [comment]
a commit on development :) sorry am on master now !

**Comment by digcat** [comment]
ok theme has been built as an amp, and tested.  available in admin tools.
landing page has been built with a bootstrap/jquery present, and login form to share
remaining set beeTheme by default, will create that as seperate issue.
