### ISSUE TITLE
permissions problem when writing to alfresco.log, share.log and solr.log in /opt/tomcat

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#67]
seeing permission denied on alfresco.log, share.log and solr.log which are trying to write to /opt/alfresco/tomcat.  its strange, that initially alfresco.log and share.log are created, with tomcat:tomcat but even when chmod 777, you still see a permission denied error

INFO: No Spring WebApplicationInitializer types detected on classpath
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: alfresco.log (Permission denied)

INFO: No Spring WebApplicationInitializer types detected on classpath
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: share.log (Permission denied)

log4j:ERROR Either File or DatePattern options are not set for appender [File].
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: solr.log (Permission denied)

**Comment by marsbard** [comment]
probably tomcat is not in the same place (cwd) and it is trying to write the logfiles elsewhere

we could make a custom log4j props and use  `<%= @alfresco_base_dir %>` or `<%= @tomcat_home %>` to put the log files in a definite place

http://blyx.com/2014/02/18/alfresco-tip-logs/

**Comment by digcat** [comment]
yes this ideal solution
