### ISSUE TITLE
iptables.sh

### ISSUE THREAD

**Issue by marsbard** [marsbard/puppet-alfresco#7]
Add iptables script into puppet config

**Comment by marsbard** [comment]
also need to firewall off the tomcat ports now we are behind apache

**Comment by digcat** [comment]
i needed to run this to ensure all ports are forwarded correctly, ie ftp 21 to 2021 etc.  this is a critical step to ensure live box functions on proxied ports.

**Comment by marsbard** [comment]
integrated into build
