### ISSUE TITLE
500 Internal Error from tomcat

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#76]
I think when the system is booting up, tomcat will provide us with the 500 Internal Error, wondering if we can override tomcats 500 page.  

http://stackoverflow.com/questions/15987212/custom-error-page-in-tomcat-7-for-error-code-500

**Comment by marsbard** [comment]
no, that's when Apache should be returning a 503 AFAIJ

**Comment by digcat** [comment]
hmm, ok so thats not working then, so reporting as a bug.  doesnt look like the 503 etc have made it into the conf.

**Comment by marsbard** [comment]
Are you sure there's not an **actual** 500 error on the tomcat server? Or does it start up eventually?

Are you sure the 500 comes from tomcat and not apache httpd?

Maybe a screen grab would be useful

**Comment by digcat** [comment]
you get an Internal Server error when trying to login before the server has completed its start up.  it lands on the dologin page, so i was thinking its tomcat.

**Comment by marsbard** [comment]
so there should be something in the logs? in /opt/alfresco/tomcat/logs/catalina.out if it's tomcat or /var/log/apache2/error.log if it's httpd

**Comment by digcat** [comment]
tested this again on latest build, looks good, so think this has been fixed.  I see the correct page, if you hit the login button before alfresco gets fully up, so im closing this one.
