### ISSUE TITLE
missing puppet on centos 7 without

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#80]
on base centos 7 ncm 

[vagrant@localhost alfresco]$ sudo ./install.sh 
loading config/ootb_pre.sh

    __    __    __    __    __    __    __    __    __    __
 __/  \__/  \__/  \__/  \__/  \__/  \__/  \__/  \__/  \__/  \__
/  \__ ORDER OF THE BEE /  \__/  \__/  \__/  \__/  \__/  \__/  \ 
\__/  \__/  \__/  \__/  \ Alfresco (TM) Honeycomb Edition   \__/
   \__/  \__/  \__/  \__/  \__/  \__/  \__/  \__/  \__/  \__/  

Idx	Param                     Value

[1]	domain_name               localhost
[2]	ssl_cert_path
[3]	initial_admin_pass        admin
[4]	mail_from_default         admin@localhost
[5]	mail_host                 localhost
[6]	mail_port                 25
[7]	alfresco_base_dir         /opt/alfresco
[8]	tomcat_home               /opt/alfresco/tomcat
[9]	alfresco_version          5.0.x
[10]	download_path             /opt/downloads
[11]	db_root_password          alfresco
[12]	db_user                   alfresco
[13]	db_pass                   alfresco
[14]	db_name                   alfresco
[15]	db_host                   localhost
[16]	db_port                   3306
[17]	mem_xmx                   3G
[18]	mem_xxmaxpermsize         256m

Please choose an index number to edit, I to install, or Q to quit
(if using Vagrant, choose Q not I and run 'vagrant up')
 -> I

0 errors
Installing...
Writing answer file config/ootb_answers.sh
Writing puppet file go.pp
Writing puppet file test.pp
which: no puppet in (/sbin:/bin:/usr/sbin:/usr/bin)
Installing puppet
which: no puppet in (/sbin:/bin:/usr/sbin:/usr/bin)
./install/modules-for-vagrant.sh: line 32: puppet: command not found
Transient failure, retrying
./install/modules-for-vagrant.sh: line 32: puppet: command not found
Transient failure, retrying
./install/modules-for-vagrant.sh: line 32: puppet: command not found
Transient failure, retrying

**Comment by marsbard** [comment]
ah it's due to that /etc/issue thing again, same as #77 -  we need to determine the osfamily (e.g. RedHat, Debian) pretty early for some of the scripts to work; 

particularly install/inc-puppet.sh needs to know osfamily before we have facter to help us

so:
```
<marsbard> I suppose if "-f /etc/debian_version" at least we know it's osfamily==Debian
<marsbard> and if "-f /etc/redhat-release"  we know osfamily==Redhat
```

**Comment by digcat** [comment]
[vagrant@localhost alfresco]$ more /etc/redhat-release 
CentOS Linux release 7.0.1406 (Core)

**Comment by marsbard** [comment]
true >.<

**Comment by marsbard** [comment]
ok kind of crap, I just changed it to parse the /etc/redhat-release file but it feels really fragile to me. want to leave it open for now and reconsider it later

**Comment by digcat** [comment]
think this is fixed using facter variables, #84

**Comment by digcat** [comment]
best wait till its compiled in travis

**Comment by digcat** [comment]
#84 tested this fixes this issue.
