### ISSUE TITLE
Instructions for puppet noobs

### ISSUE THREAD

**Issue by jpotts** [marsbard/puppet-alfresco#85]
Seems like we need a bit of a scene setter or intro for people completely new to puppet (as am I).
Running on a Centos 6.5 vagrant machine I did not yet have puppet installed. I figured out I needed to enable the puppet I figured out that I needed to enable the dependencies and the install puppet-server with yum:
sudo rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm
sudo yum install puppet-server
But that got me thinking about whether I really wanted puppet server on the image or if the agent would have sufficed.

**Comment by digcat** [comment]
Hi Jeff

Yes, vagrant does add some confusion, where it doesn't need to.  If you 
have spun a vm using vagrant, then any packages vagrant has added to the 
vm, puppet will carry on, unless it causes some conflict.  So once you 
are in your vm, you do need to hit I to install.  Also I just noticed on 
the docs, you need to run with root permissions,

so run

sudo ./install.sh from a user account, this will setup your install. 
Also a few commits are on master, for centos 7 set for next release.

the genius with puppet, is its ability to be rerun, so make a config 
change and rerun, or use the puppet apply command.

**Comment by marsbard** [comment]
This is supposed to install puppet for you https://github.com/marsbard/puppet-alfresco/blob/master/config/ootb_install.sh - it gets run from ./install.sh

I'm not sure exactly why it caused a problem for you; looks like I probably need to run through the 'clean install' scenario once more.

**Comment by digcat** [comment]
hi martin

those commits on master fixed this issue, related to choosing the 
correct version from forge, if jeffs on tag ? or master?
cheers

Daren

**Comment by marsbard** [comment]
I guess he is using the released version; we probably need to clean up the issue list and make a point release

**Comment by digcat** [comment]
fixed in dev-1.1
