### ISSUE TITLE
access using alfresco android mobile 1.5.1

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#93]
when trying to access the repository using alfresco mobile 1.5.1 cannot connect to repo.

Installed certificate as required, 

only entry seen in access log for apache proxy, no entries in catalina.out

x.x.x.x - - [26/Jun/2015:06:18:42 +1000] "PRI * HTTP/2.0" 400 226 "-" "-"
x.x.x.x - - [26/Jun/2015:06:18:44 +1000] "PRI * HTTP/2.0" 400 226 "-" "-"
x.x.x.x - - [26/Jun/2015:06:18:47 +1000] "PRI * HTTP/2.0" 400 226 "-" "-"

this is seen in apaches access log file on trying connection from app.

**Comment by marsbard** [comment]
Any way to check if that cert is correctly installed? If android/ios were not clear about the certificate they may not even make a request out. AFAIR that is the android behaviour anyway (unless the app allows looser cert checking IIRC)

**Comment by digcat** [comment]
yep, ive spun up a full ssl, and the repo is working fine in share. and have loaded the the cert onto the phone, what im more confused by is the above entries hit the apache log, but nothing is hitting catalina,

**Comment by digcat** [comment]
thought perhaps the additional security added to the ssl was issue but confirmed using python cmislab, i have working access to the repo.

**Comment by digcat** [comment]
reverting to an older client, i see similar thing, so think something we are doing with the redirects is causing this issue

x.x.x.x - - [28/Jun/2015:01:37:41 +1000] "GET /alfresco/api/-default-/public/cmis/versions/1.0/atom/ HTTP/1.1" 301 286 "-" "Apache Chemistry OpenCMIS/0.0"
x.x.x.x - - [28/Jun/2015:01:37:44 +1000] "GET /alfresco/cmisatom HTTP/1.1" 301 250 "-" "Apache Chemistry OpenCMIS/0.0"
x.x.x.x - - [28/Jun/2015:01:37:48 +1000] "GET /alfresco/service/cmis HTTP/1.1" 301 254 "-" "Apache Chemistry OpenCMIS/0.0"

**Comment by digcat** [comment]
this looks related although quite old, https://issues.alfresco.com/jira/browse/MNT-2838

**Comment by digcat** [comment]
fixed 1.5.2.254
