### ISSUE TITLE
uploader plus module

### ISSUE THREAD

**Issue by digcat** [marsbard/puppet-alfresco#98]
Im seeing an issue with uploader plus module with ubuntu 14.04 and java 8

http://pastebin.com/Qzq15D5P

uploader plus not loading

**Comment by marsbard** [comment]
Notice: /Stage[main]/Alfresco::Addons/Exec[apply-addons]: Dependency Exec[safe-retrieve-addons::uploader-plus-share] has failures: true

It looks like the _download_ of the uploader-plus share module failed for some reason

**Comment by digcat** [comment]
yes something strange on my bb have just tried on external vps and its all good
